
package info.serdroid.pergamon.ws.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "CalculatorWebService", targetNamespace = "http://ws.pergamon.serdroid.info/", wsdlLocation = "src/main/resources/wsdl/CalculatorWebService.wsdl")
public class CalculatorWebService
    extends Service
{

    private final static URL CALCULATORWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATORWEBSERVICE_EXCEPTION;
    private final static QName CALCULATORWEBSERVICE_QNAME = new QName("http://ws.pergamon.serdroid.info/", "CalculatorWebService");

    static {
        CALCULATORWEBSERVICE_WSDL_LOCATION = info.serdroid.pergamon.ws.client.CalculatorWebService.class.getResource("src/main/resources/wsdl/CalculatorWebService.wsdl");
        WebServiceException e = null;
        if (CALCULATORWEBSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'src/main/resources/wsdl/CalculatorWebService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CALCULATORWEBSERVICE_EXCEPTION = e;
    }

    public CalculatorWebService() {
        super(__getWsdlLocation(), CALCULATORWEBSERVICE_QNAME);
    }

    public CalculatorWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns CalculatorWS
     */
    @WebEndpoint(name = "CalculatorWSPort")
    public CalculatorWS getCalculatorWSPort() {
        return super.getPort(new QName("http://ws.pergamon.serdroid.info/", "CalculatorWSPort"), CalculatorWS.class);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATORWEBSERVICE_EXCEPTION!= null) {
            throw CALCULATORWEBSERVICE_EXCEPTION;
        }
        return CALCULATORWEBSERVICE_WSDL_LOCATION;
    }

}
